name: CookieClicker
main: com.github.l33m4n123.cookieclicker.CookieClicker
version: 1.5
commands:
   cookieclicker:
      description: You can play CookieClicker with this
      permission: cookie.clicker
      usage: /cc start or /cc buy [upgrade] or /cc prices or /cc leaderboard
      aliases: cc